### ISSUE TITLE
There's no documentation?

### ISSUE THREAD

**Issue by anhzf** [kynikos/lib.js.firestore-orm#1]

**Comment by kynikos** [comment]
Indeed, this library is still under heavy development, and the coverage of the native API is still quite partial... The closest you get to some documentation is by looking at the tests and using them as examples.

**Comment by anhzf** [comment]
> Indeed, this library is still under heavy development, and the coverage of the native API is still quite partial... The closest you get to some documentation is by looking at the tests and using them as examples.

yeaah, thanks for the reply. I've looked at tests, I'm only not sure what I'm doing

**Comment by kynikos** [comment]
For the moment this is how it basically works (I haven't even tested this example), but bear in mind it could radically change in the future, that's why I'm not maintaining documentation at the moment:
```javascript
const firebaseAdmin = require('firebase-admin')
const {Database, CollectionSetup, DocumentSetup, DocumentSchema,
  FieldString} = require('@kynikos/firestore-orm')

const docSetup1 = new DocumentSetup({
  match: true,
  schema: new DocumentSchema(
    new FieldString('bla'),
  ),
  structure: {
    getBla: async (doc) => {
      const snapshot = await doc.get()
      return snapshot.get('bla')
    },
  },
})

const collSetup1 = new CollectionSetup({
  match: 'sampleColl',
  documents: [
    docSetup1,
  ],
  structure: {
    doc: (docId, coll) => coll.doc(docId),
    iterDocs: (coll) => coll.iter(docSetup1),
  },
})

const database = new Database({
  firebaseAdminApp: firebaseAdmin.initializeApp(),
  structure: {
    sampleColl: 'sampleColl',
  },
  collections: [
    collSetup1,
  ],
})

const sampleColl = database.sampleColl
const foobar = sampleColl.doc('foobar')

async function main() {
  await foobar.create({bla: 'blabla'})
  const foobarBla = await foobar.getBla()
  console.log(foobarBla)
  for await (const snapshot of sampleColl.iterDocs()) {
    console.log(snapshot.get('bla'))
  }
}

main()
```

**Comment by anhzf** [comment]
Nice, thanks for ur explanation I really appreciate it! Good job!

**Comment by kynikos** [comment]
Thanks for the encouragement, if you're interested and keep experimenting, I also accept PRs for documentation ;)
